fragment ProjectParts on Project {
  __typename
  title
  slug
  featured
  status
  date
  category
  tagline
  client
  shortDescription
  description
  credits
  tags
  heroImage
  gallery {
    __typename
    layout
    type
    image
    videoUrl
    caption
  }
}

fragment SettingsParts on Settings {
  __typename
  categories
  availableTags
}

fragment SiteSettingsParts on SiteSettings {
  __typename
  contactEmail
  cvFile
  socialLinks
}

fragment InfoParts on Info {
  __typename
  bio
  availability
  capabilities
  pressAndAwards {
    __typename
    title
    url
  }
}
